# These are supported funding model platforms

github: [https://github.com/ChlleXanDev/]  # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://www.youtube.com/@telesandifestival6955', 'https://www.youtube.com/@officialtels', 'https://www.youtube.com/@SENIMEDIA', 'https://www.youtube.com/channel/UCehQMGUaFgzKZ8RoNT-Oc0w'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
